### ISSUE TITLE
Elements of breadcrumb are not linkable (when they should)

### ISSUE THREAD

**Issue by chekmare** [poteto/ember-crumbly#106]
Let's assume we've got the following route hierarchy: /admin/users and admin route has following definition:

```javascript
export default Ember.Route.extend({
    breadCrumb: {
        title: 'Some title'
    }
});
```
When you enter the route 'admin', the admin breadcrumb is not linkable since it is the last element of the breadcrumb. Unfortunately, when you proceed to 'admin.users' that admin route is still not linkable. Reload of the page fixes the problem.

The issue here is that when you first enter the route you retrieve breadCrumb object from the route and modify it injecting linkable property. And this property value is used from this moment on.

The fix I guess is easy: use a copy of the object. Something along the lines in _lookupBreadCrumb:

```javascript
const routeBreadCrumb = get(route, 'breadCrumb');
if (typeOf(routeBreadCrumb) === 'null') {
   return;
}
let breadCrumb = Ember.assign({
   title: classify(name),
   linkable: crumbLinkable,
   path
}, routeBreadCrumb);
return breadCrumb;
```

So far one could use workaround:

```javascript
export default Ember.Route.extend({
    breadCrumb: Ember.computed(function() {
        return {
            title: 'Some title'
        };
    }).volatile()
});
```

**Comment by dguettler** [comment]
Resolved by #111
