### ISSUE TITLE
Hide element if no crumbs

### ISSUE THREAD

**Issue by knownasilya** [poteto/ember-crumbly#109]
Currently the breadcrumb element still shows up and takes up space even if there are no crumbs.

**Comment by dguettler** [comment]
@knownasilya can you give an example?
Based on existing acceptance tests this should not be the case
See https://github.com/poteto/ember-crumbly/blob/master/tests/acceptance/integration-test.js#L33

**Comment by knownasilya** [comment]
Might be related to the root index issue.
