### ISSUE TITLE
manually set link

### ISSUE THREAD

**Issue by dbinetti** [poteto/ember-crumbly#112]
I have a use case that doesn't seem to be covered in the docs. 

I have a resource that has several sub-routes (details, relatedobjects, morerelatedobjects) and I use bootstrap tabs to keep a consistent interface.  This means that when I link to a particular resource, I link directly to `/details`, which provides data related to the resource itself (as opposed to the other tabs, which show arrays of the related objects.)

However, when I use `crumbly` it links directly to the resource without the `details`, meaning that it renders an empty page.  I've tried using a redirect on the 'naked' resource to transition to the `details` sub-route, but either I'm using that method incorrectly or it simply isn't working.

I see how to overwrite the text in the breadcrumb but how do I overwrite the linked route itself?

Thanks...

**Comment by dguettler** [comment]
@dbinetti just published ember-crumbly@1.0.6 which now allows you to specify a `path` on the `breadCrumb`

**Comment by dguettler** [comment]
Resolved in 80d316ff0a6db1e7ddaa9600ecea885e8dc87f7a
