### ISSUE TITLE
Fix install updated version with npm

### ISSUE THREAD

**Issue by dmarkin** [poteto/ember-crumbly#120]
Please, fix version which installed from npm (now it is non-actual version with getOwner issue)

**Comment by peter-watters** [comment]
Hi,

I just started using this today and it's awesome but similar to **dmarkin** it is throwing a deprecation warning for the getOwner issue which is already fixed it seems. 

Can you please tag and release the latest code so npm picks it up properly? 

Thanks!

**Comment by ivorscott** [comment]
If you are waiting for a fix, just go to 
node_modules/ember-crumbly/addon/components/bread-crumbs.js and comment out the following
```
import Ember from 'ember';
import layout from '../templates/components/bread-crumbs';
// import getOwner from 'ember-getowner-polyfill';
```
:)

**Comment by dguettler** [comment]
1.0.7 Released!
