### ISSUE TITLE
Computed property crumbs not updating

### ISSUE THREAD

**Issue by jeloba** [poteto/ember-crumbly#124]
According to the README bread crumbs that are computed property should be updated when their dependent values change.

> In this case, if the name property of model is modified, the breadcrumb will be updated automatically.

However since d852852ea2b67cddcb8ee3e769e0a478d8cf1e46 crumbs are simply copied and not watched. This means bread crumbs are not updated after they where rendered once.

**Comment by CezaryH** [comment]
any news on that ?

**Comment by knownasilya** [comment]
This is still an issue, does anyone have an idea on how to refactor this to make it work?
