### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ondrejsevcik** [poteto/ember-crumbly#137]
Hi, I like the idea of ember-crumbly but it seems that there is a bunch of PR that are not being resolved and the same goes for issues. Is this project dead?

**Comment by scottkidder** [comment]
I came here with the same question, and it appears to be so.

**Comment by velrest** [comment]
If it is in fact dead ( looks a lot like it ) it would be helpful to add this to the readme so new users dont build their apps based on this.

**Comment by scottkidder** [comment]
I have just learned about https://github.com/adopted-ember-addons so maybe this project could find it's new home there? @dguettler @poteto
