### ISSUE TITLE
Ember-copy should be a dependency

### ISSUE THREAD

**Issue by cah-briangantzler** [poteto/ember-crumbly#141]
When upgrading to ember-crumbly 3.0.0 I received and error stating it could not find ember-copy. 

I see it is in the dev-dependencies, should it be in dependencies?

**Comment by dguettler** [comment]
fixed by #142

**Comment by cah-briangantzler** [comment]
Thanks, I had done as you suggested prior to posting the message, in case there were any other missing dependencies. Posted this issue to hopefully help other people resolve the problem

**Comment by dguettler** [comment]
3.0.1 fixes the issue
