### ISSUE TITLE
First element in route with null title still creates forward slash

### ISSUE THREAD

**Issue by mkandefer** [poteto/ember-crumbly#18]
When I create a route where the first part of the route is given a null titled breadcrumb, the forward slash still appears.

Route is defined as Admin / Profiles / Profile.

Admin's breadCrumb title is set to null, and appears as:

/ Profiles / Profile

Is there a way to get it to display as: Profiles / Profile

**Comment by poteto** [comment]
@mkandefer This is already how it works, you have to set `breadCrumb: null` on the `index` route for that parent. 

E.g. If the first part of your route is `foo`, you should set the breadcrumb on `foo.index`.

Hope that helps!
