### ISSUE TITLE
[Feature Request]: Linkable false issue in child views

### ISSUE THREAD

**Issue by abhilashlr** [poteto/ember-crumbly#21]
If the route is "foo.baz" and setting "baz" as "linkable:false", and having "edit" route as child of "baz" renders the breadcrumb as "foo > baz > edit" where
foo - linkable
baz - non linkable
edit - linkable.

**Comment by poteto** [comment]
What's the issue? The `linkable` attr does not flow down to child routes

**Comment by abhilashlr** [comment]
@poteto yes that is exactly the problem.
The exact use case is:
Home / Abhilash L R - Here only, Home will be linkable and Abhilash L R would be non-linkable
Edit profile route will have breadcrumb as:
Home / Abhilash L R / Edit - In which case, Edit should be non-linkable and Abhilash L R should be linkable.

Ideally, I would like to have all child end points as non linkable and everything before that as linkable.
