### ISSUE TITLE
using with ember generate route fails

### ISSUE THREAD

**Issue by efx** [poteto/ember-crumbly#25]
Thanks for publishing this addon; it looks helpful but I ran into an issue using it.
ember-cli 0.2.5
ember 1.13.0-beta.2

1. ember new crumbly-bugfix
2. ember generate route somewhere
3. ember serve
Upon navigating to localhost:4200/somewhere the browser console says
```
Uncaught Error: Assertion Failed: [ember-crumbly] `route:somewhere.index` was not found
``` 
bower.json
```json
{
  "name": "crumbly-bugfix",
  "dependencies": {
    "ember": "1.13.0-beta.2",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.0.0-beta.18",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4",
    "ember-qunit": "0.3.3",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.15",
    "jquery": "^1.11.1",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1"
  }
}
```
My app/templates/application.hbs has 
```
<h2 id="title">Welcome to Ember.js</h2>
{{bread-crumbs tagName="ul" outputStyle="foundation" linkable=false}}
{{outlet}}
```

**Comment by poteto** [comment]
As the warning suggests, you need to generate the route `somewhere.index`.

**Comment by efx** [comment]
I see. All routes need to have an index so crumbly can see them. 
`ember generate somewhere/index` fixes it. Thanks!

**Comment by poteto** [comment]
Only routes with child routes need an `index` route explicitly defined. If it is a 'standalone' route, an `index` isn't necessary!

**Comment by abhilashlr** [comment]
I fixed this by simply saying in the route:
this.route('somewhere', function() {});

instead of having it as: this.route('somewhere');
