### ISSUE TITLE
addon broken in ember-cli 0.2.7

### ISSUE THREAD

**Issue by wolfbiter** [poteto/ember-crumbly#26]
I read your post in ember weekly and want to use your component - but I can't get it working in my ember cli project. See terminal output. I also tried again after `npm run clean:all` (see below), same issue.

node v0.12.4
ember-data v1.0.0-beta.18

```
    "clean": "rm -rf ./node_modules ./bower_components ./dist ./tmp",
    "clean:all": "npm run clean && npm cache clean && bower cache clean"
```

![image](https://cloud.githubusercontent.com/assets/1360563/8043091/6b6fd636-0dd8-11e5-97a7-93809626a0b3.png)

**Comment by poteto** [comment]
This looks like an `ember-browserify` issue – https://github.com/ef4/ember-browserify/issues/35.

**Comment by wolfbiter** [comment]
@poteto thanks so much for that, you're totally right - sorry for the red herring
