### ISSUE TITLE
Assertion Failed: [ember-crumbly] `route:loading.index` was not found

### ISSUE THREAD

**Issue by tommyblue** [poteto/ember-crumbly#35]
This error is shown when I move from a page with ember-crumbly to a page without it.
The next page isn't loaded, so this error totally breaks the page navigation.
I don't have a loading route, but I have a `loading.hbs` template.

```
DEBUG: -------------------------------
ember.debug.js:4888 DEBUG: Ember                    : 1.12.0
ember.debug.js:4888 DEBUG: Ember Data               : 1.0.0-beta.18
ember.debug.js:4888 DEBUG: jQuery                   : 2.1.4
ember.debug.js:4888 DEBUG: Ember Simple Auth        : 0.8.0
ember.debug.js:4888 DEBUG: Ember Simple Auth Devise : 0.8.0
ember.debug.js:4888 DEBUG: -------------------------------
```

**Comment by ssured** [comment]
Same problem for me using Ember 1.12.1

**Comment by topaxi** [comment]
Got the same problem with top-level error routes (`templates/error.hbs` or `error/template.hbs`)

**Comment by poteto** [comment]
Thanks for reporting! Will have a fix out today when I get some time to work on it.

**Comment by mmahalwy** [comment]
Any word on this? Still having the same problem...
