### ISSUE TITLE
[Intermittent Issue] Setting title in breadCrumb object from route, doesn't enable linkable while moving to child route.

### ISSUE THREAD

**Issue by abhilashlr** [poteto/ember-crumbly#42]
Let us assume, the route is say **foo > baz** and another route **xyz > baz**

Steps to reproduce:
1. In routes/foo.js, pass title as "FOO doesn't hyperlink itself"
2. Don't set linkable
3. Refresh the baz page. You can see the foo with hyperlink and baz as non-linkable. [which is fine]
4. Navigate to the other route xyz and do a page refresh. Come back to baz via foo, you can see foo is not hyperlink enabled.

Please share your thoughts if it happens to others as well.

I can try for a possible fix, could take some time though.

**Comment by dguettler** [comment]
@abhilashlr can you give a more explicit example?
I'm not entirely sure I understand `foo` and `xyz`. Are you talking about something like this
```
/customers/1/baz
/customers/2/baz
```

**Comment by fsmanuel** [comment]
@dguettler I'm not sure if this is already fixed but the latest stabel version has the problem that when you click on `baz` the model route is still disabled.

**Comment by tpetrone** [comment]
This is happening here too.
*_SoMeTiMeS_*  (o.O) When navigating to `foo/bar/baz`, `bar` is not clickable

**Comment by tpetrone** [comment]
I can confirm this, if only `title` is set.
Not setting `title` makes it to work as expected.

**Comment by dguettler** [comment]
Resolved by #111

**Comment by Navaneeth-pk** [comment]
Still cannot use dynamic routes as path.
