### ISSUE TITLE
Home link prefix any route

### ISSUE THREAD

**Issue by trong291990** [poteto/ember-crumbly#46]
How can to add Home link before any breadcrumb , for example : 
Home/Users ( routes/users/index)
Home/Users/new (routes/users/new)
Thanks

**Comment by abhilashlr** [comment]
I guess you might have to use a custom bread crumb template to render the Home link.

**Comment by trong291990** [comment]
Yes, is it supported ?

**Comment by abhilashlr** [comment]
yes, all ember components do support you to add your own template (override)

create a component in your app folder same as bread-crumbs with template.hbs being your custom template. 

until a way is found to achieve it through component's properties/config, this could help you out.

**Comment by ivaylopivanov** [comment]
Just create a templates/components/bread-crumbs.hbs template and use the following

```js
<li>{{#link-to 'index' class=linkClass}}Home{{/link-to}}</li>
{{#each routeHierarchy as |route|}}
  {{#if hasBlock}}
    {{yield this route}}
  {{else}}
    {{bread-crumb route=route breadCrumbs=this}}
  {{/if}}
{{/each}}
```
