### ISSUE TITLE
[Suggestion] Make the `breadCrumb` optional by default (or make this configurable).

### ISSUE THREAD

**Issue by VasilioRuzanni** [poteto/ember-crumbly#47]
This would help a lot when you need to integrate that into existing product but want to only show the breadcrumbs for specific pages and avoid the need to set `breadCrumb: null` all over every route (there might be tons of routes).

Aside from that, there might be a route that is not `index` (e.g., top-level `about` route) and the guessed name is incorrect (there is no `about.index` but there is `about`). In a bigger project this all just breaks apart but with `breadCrumb` route attribute being optional by default (or configured to be optional) these checks can be just silently bypassed.

**Comment by xcambar** [comment]
:+1: on this.

The defaults that I can think of right now:
* opt-in: `breadCrumb: null` by default. The devs have to explicitely activate a breadcrumb
* opt-out: `breadCrumb: {}` by default. The devs have to explicitely deactivate a breadcrumb

My personal preference goes to opt-in, fwiw.

**Comment by ivanvanderbyl** [comment]
I've solved this in my app by declaring `breadCrumb: null` in a `BaseRoute` which all other routes extend.

**Comment by xcambar** [comment]
Thank you. Your solution does the job, such as reopening `Ember.Route`.

But the real point is that it's unfortunate to see your app break right after installing an addon, it doesn't make for a very smooth developer experience, that's what @VasilioRuzanni and I experienced and why we're offering to discuss alternatives.

**Comment by dguettler** [comment]
Closing this for now. Having a top level `customers` route which renders breadcrumbs work fine with the latest version. No need to explicitly define `breadCrumb` in the route.
