### ISSUE TITLE
Could not find module 'ember-new-computed'

### ISSUE THREAD

**Issue by mk-conn** [poteto/ember-crumbly#49]
After upgrading to 1.0.0 this error pops up:

```
Uncaught Error: Could not find module `ember-new-computed` imported from `ember-crumbly/components/bread-crumbs` : loader.js:110
```
Already removed node_modules and cleared cache, npm installed again and everything but error still remains ... what could cause this issue? 

```
DEBUG: Ember      : 2.1.0
DEBUG: Ember Data : 2.1.0
DEBUG: jQuery     : 1.11.3
DEBUG: -------------------------------
```

**Comment by poteto** [comment]
Sorry about that, https://github.com/poteto/ember-crumbly/releases/tag/1.0.1 should address this issue.

**Comment by mk-conn** [comment]
Yep, it is fixed. Thx!
