### ISSUE TITLE
 Error: Assertion Failed: [ember-crumbly] `route:some-route.index` was not found

### ISSUE THREAD

**Issue by mk-conn** [poteto/ember-crumbly#50]
Happens, when there is no 'route'/index route setup in the project. Dunno if the pull request I created would work with 1.0.1 ? https://github.com/poteto/ember-crumbly/pull/34

**Comment by efx** [comment]
+1

**Comment by mk-conn** [comment]
Thought I could solve this quickly but I wasn't able to since I have to urgently work on other stuff so I closed the pull request (tests where failing and stuff.. ). So, would be nice if Lauren could solve this?
