### ISSUE TITLE
Ignore loading/error routes

### ISSUE THREAD

**Issue by danielspaniel** [poteto/ember-crumbly#62]
I am getting errors when crumbly can't find a loading route. This is similar to #60, but the twist is these routes, although they don't exist, should not be included in the crumb ( unlike index or other routes that don't explicitly exist but are still breadcrumbable routes. )
 Anyway .. I can submit PR, but wanted to wait till the master branch is updated. Is that going to happen anytime soon?

**Comment by nem035** [comment]
+1

**Comment by sylwiaeb** [comment]
Any chance to get this fix soon? Having the same issue.

**Comment by danielspaniel** [comment]
In the meantime you could use my fork:
  put this in package.json and run npm install
 "ember-crumbly": "git+https://github.com/danielspaniel/ember-crumbly.git#a330602b51624297cea1f31e137bbacd15631d13" 

  yeah .. i wish whoever was maintaining this would give us a sign. I realize this whole addon needs rewriting and I am willing to rewrite it but there are too many dangling branches that keeps me tied down.

**Comment by sylwiaeb** [comment]
> "ember-crumbly": "git+https://github.com/danielspaniel/ember-crumbly.git#a330602b51624297cea1f31e137bbacd15631d13"

:+1:

**Comment by jameshoward** [comment]
I'm seeing a problem where Ember is transitioning to a route such as `index_loading`. Although 16c80451b17b94116f4fe07fe6ab31712ef3480e excludes `loading`, it won't exclude `index_loading`. Presumably this same problem would occur for other routes' loading routes e.g. `edit_loading`.

**Comment by danielspaniel** [comment]
Since this addon in no longer being maintained ..
I take the installed addon code .. then I make my own breadcrumb component which overrides the one provided here.
And then change a few things like:

```js
  _lookupRoute(routeName) {
    const container = getOwner(this);
    const route = container.lookup(`route:${routeName}`);
    // Dans fix for NOT matching loading or errorpages
    if (routeName.match(/loading|error/)) {
      return null;
    }
    return route;
  },
```

there might be a few other things I did .. but that is the basic idea .. and should get you started

**Comment by jameshoward** [comment]
Is it no longer maintained? Where did you see that? The last commit / release was only just over a month ago.

**Comment by poteto** [comment]
It is still being maintained, but admittedly very poorly. Feel free to use @danielspaniel's fork, I will be addressing these issues when I get the time to do so

**Comment by poteto** [comment]
P.S. You can still submit a PR, `master` is updated

**Comment by alvinvogelzang** [comment]
@danielspaniel thanks the fix is working. I think it's a good thing to ignore these routes by default right? Only problem I see is that this fix will also ignore routes which are named with 'loading' or 'error' on purpose.

**Comment by danielspaniel** [comment]
@poteto .. thanks for finally getting back on this. I would rather just help rewrite the whole thing since there is more to it than just this small fix. If you like I can work on it this weekend or next .. because this component needs a rewrite. 
@alvinvogelzang: hmmm .. nice special case there .. but how to get around that is very tricky

**Comment by poteto** [comment]
@danielspaniel Yeah that'd be awesome, sorry I dropped the ball on this addon – I've taken on too many things haha. If you'd like, I can add you as a collaborator

**Comment by danielspaniel** [comment]
@poteto .. I figured that was the case, and I know you have to make priorities for things, and this addon is way less important than composable helpers  ( sorry in advance if that offends anyone .. )
 so, yeah , if you want to add me I can just go to town, but would be funner to work together with someone, even if not you then if you can delegate an appropriate minion ( sorry if that offends anyone .. but that is a joke )

**Comment by abhilashlr** [comment]
Daniel, let me know if you need help. I would love to contribute

**Comment by danielspaniel** [comment]
@poteto .. can you make me collaborator then .. i will get started on this 
@abhilashlr .. when can you start .. I can work on it this weekend or next.

**Comment by abhilashlr** [comment]
It's a weekend already here 😂 we can start off immediately☺

**Comment by danielspaniel** [comment]
@abhilashlr .. sorry for delay .. I was looking things over and seeing what needs to be done and whatnot. 
 you on SH?

**Comment by abhilashlr** [comment]
Sorry what is SH?

**Comment by danielspaniel** [comment]
screen hero

**Comment by danielspaniel** [comment]
i just pushed my refactors to the danielspaniel fork of this repo .. so if you pull that you will see what I have started 
what i think is needed is some more tests to show that the index or error or loading routes are not shown.
can you ponder how to do that .. and or let me know what else you want to touch up

**Comment by danielspaniel** [comment]
actually .. i just tested on ember 1.11 and i broke the heck out this so let me ask if we can do version for ember 2 starting now?
@poteto .. you up for a version bump that requires ember 2 and up?

**Comment by dguettler** [comment]
@danielspaniel Is this still an issue? If so is there a PR to fix this?

**Comment by danielspaniel** [comment]
I think I did not make a PR because the previous maintainer was so flakey I never could get any feedback. But I can put it out there if you like.

**Comment by dguettler** [comment]
@danielspaniel if you could give a quick example how to demonstrate the issue this would be helpful as a first step.

**Comment by dguettler** [comment]
Closing this, if it's still an issue please give an example and I'll re-open
