### ISSUE TITLE
breadCrumb override is ignored on a root route

### ISSUE THREAD

**Issue by sergproua** [poteto/ember-crumbly#83]
Consider the following routes.

When navigating to http://localhost:4200/customers the breadcrumbs generated is 
1. Customers 

However when navigating to http://localhost:4200/customers/1 the breadcrumbs generated is 
1. OverrideMe! 
2. Profile.

router.js

```
  this.route('customers', function () {
    this.route('profile', {path: '/:id'});
  });
```

routes/customers.js

```
export default Ember.Route.extend({
  breadCrumb: {
    title: 'OverrideMe!'
  },
});
```

**Comment by dguettler** [comment]
It looks like ember-crumbly is looking at the `customers.index` route for the override.
So if you define the override on `customers.index` it is correctly applied for both cases.

**Comment by mrkirchner** [comment]
Ran into the same issue i noticed that in:

bread-crumbs.js

`_guessRoutePath(routeNames, name, index) {
    const routes = routeNames.slice(0, index + 1);

    if (routes.length === 1) {
      let path = `${name}.index`;

      return (this._lookupRoute(path)) ? path : name;
    }

    return routes.join('.');
  },`

Removing the .index on the path seemed to fix my issue but i do not know why it was there in the first place or if it is truly needed

**Comment by knownasilya** [comment]
Also seeing this, weird that it requires the index, when the index could have it's own crumb. This is most certainly a bug.

**Comment by dguettler** [comment]
Related #99 and #104

**Comment by dguettler** [comment]
See #104
