### ISSUE TITLE
breadCrumb can be a computed property, but no documentation/tests

### ISSUE THREAD

**Issue by christophersansone** [poteto/ember-crumbly#84]
I ran into a situation where the breadCrumb title was stale by the time the page was rendered.  Long story short, `afterModel` on the new route may wind up being called before `deactivate` on the old route, but model changes are rolled back on `deactivate`.  As a result, the breadcrumb was showing the unsaved title that was eventually rolled back.

One method for resolving this situation is to define `breadCrumb` as a computed property.  The good news is that it works:

```
breadCrumb: Ember.computed('controller.model.name', {
  get() {
    return { title: this.get('controller.model.name') };
  }
})
```

The trouble is that I did not see any documentation or tests accordingly.  I'm wondering if this is a supported feature, and if not, should it be?

**Comment by poteto** [comment]
This is supported and working as intended since we fetch the breadcrumb using `Ember.get`. I agree it should be documented though.

**Comment by christophersansone** [comment]
Thanks @poteto! Here's a PR. :smile:
