### ISSUE TITLE
Integration testing fails when crumbly is defined in a component	

### ISSUE THREAD

**Issue by sergproua** [poteto/ember-crumbly#88]
I'm refactoring my application and moved crumbly from a route to a component template. Now my component integration test fails with an error below:

> Assertion Failed: [ember-crumbly] Could not find a curent route

Eventually I want to add testing and ensure proper path and links have been rendered but stuck here. I've tried many suggestions like using qunit "visit" method, StartApp helper and could not get test to pass. Any help is greatly appreciated.

```
import { moduleForComponent, test } from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';

moduleForComponent('main-user', 'Integration | Component | main user', {
  integration: true,
});

test('it renders', function (assert) {
  this.render(hbs`{{my-new-component-with-crumbly}}`);
  assert.ok(true);
});
```

**Comment by dguettler** [comment]
@sergproua routes are not available within integration tests. So we can't determine the current route, which causes above assertion to fail.
ember-crumbly relies on
```
  currentUrl: readOnly('applicationRoute.router.url'),
  currentRouteName: readOnly('applicationRoute.controller.currentRouteName'),
```
to read the `currentUrl` and `currentRouteName`. So if you would want to use this in an integration test you'd need to stub out the `applicationRoute` (route:application), which gets injected into the component, and have the stub return expected values.

You can read more here https://guides.emberjs.com/v2.0.0/testing/testing-components/#toc_stubbing-services

**Comment by poteto** [comment]
I would recommend using ember-crumbly in a top level template and then passing in the data into your component as an attribute instead.

**Comment by dguettler** [comment]
Closing for now, this is a limitation we can't easily get around as without routes there are no bread crumbs.
