### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by jesseditson** [poteto/ember-crumbly#90]
This project has a great rating on ember observer, but has a few bugs, broken demo page, and broken CI. Also looks like the PRs are fairly active, wanted to see if you were still working on this.

If the original author has moved on, does someone from the PR thread want to step up and take over? npm still sees this package getting a fair amount of use, but without a maintainer I'll probably switch us to something else.

**Comment by poteto** [comment]
It is still active, but I haven't had as much time as I'd like to work on it. I would be very happy to add someone as a collaborator for them to step in when I can't afford a spare cycle

**Comment by fsmanuel** [comment]
@poteto I'm here to help. If you give me commit permissions I'll review the PR's and give some guidance with the open issues.

**Comment by poteto** [comment]
@fsmanuel Done. Thanks for helping out!
