### ISSUE TITLE
Problems with */* and */index routes

### ISSUE THREAD

**Issue by andrewfan** [poteto/ember-crumbly#99]
I have a situation when i want to show breadcrumbs when user visits 
`routeWithBreadcrumbsProperty/*` route and dont what to show it when user visits 
`routeWithBreadcrumbsProperty/index` route 
and i in the first case it make sense to use `routeWithBreadcrumbsProperty` route to get `breadCrumb` title and in the second case it make sense to use `routeWithBreadcrumbsProperty/index` route
unfortunately addon always wants to use  `routeWithBreadcrumbsProperty/index` property but if route level is > 0 eg. 'foo.bar' `foor.bar` route is using
the workaround that i use right now is:
`routeWithBreadcrumbsProperty` checks if transition target is not equal to `routeWithBreadcrumbsProperty/index` and then sets correct breadcrumb to `routeWithBreadcrumbsProperty/index` route also i use  `routeWithBreadcrumbsProperty/index`  activate/deactivate hooks to populate or clear `breadCrumb` object

**Comment by dguettler** [comment]
Same issue as #104
